keepalive:
	curl -i --location --request POST 'http://localhost:54321/functions/v1/' \
		--header 'Authorization: Bearer $$BEARER_TOKEN' \
		--header 'Content-Type: application/json' \
		--data '{"name":"Functions"}'
