import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Take The Burns Depression Checklist
        </h1>

        <p className={styles.description}>
          From{' '}
          <a href="https://www.amazon.com/Feeling-Good-New-Mood-Therapy-ebook/dp/B009UW5X4C">
            Feeling Good: The New Mood Therapy, by
            David D. Burns
          </a>
        </p>

        <table className="table-auto">
          <tbody>
            <tr>
              <td>
                Feeling sad or down in the dumps
              </td>
              <td>TODO</td>
            </tr>
          </tbody>
        </table>
      </main>
    </div>
  );
};

export default Home;
