name: CI - edge functions

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'backend/supabase/functions/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 'backend/supabase/functions'

    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - run: deno lint
