name: frontend-ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  jest:
    # TODO: update branch
    uses: mdzhang/burns-depression/.github/workflows/reusable.yml@add-linter
    with:
      cmd: test

  eslint:
    uses: mdzhang/burns-depression/.github/workflows/reusable.yml@add-linter
    with:
      cmd: lint
