name: frontend-test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  jest:
    # TODO: update branch
    uses: ./.github/workflows/frontend-reusable.yml@add-linter
    with:
      cmd: test
